### ISSUE TITLE
Investigate sorting and translations issues

### ISSUE THREAD

**Issue by slomo** [liqd/a4-opin#1015]
We filter and sort organisations by title which is an translated property. Here are some issues:

  - translated title lead to organisations showing up multiple times (but with same text)
  - but there is a limit clause on the query, resulting in other organisations being dropped
 
Solutions:

  - not translate title
  - not translate anything
  - move to our own translated model implementation from wagtail (but might still be difficult)

**Comment by gereonrahnfeld** [comment]
From my perspective we could skip the translation of the organisation title and the organisation details because most organisation do not use this functionality - they have a working language in which they conduct their participation processes and which they use for organisation title and description as well.

**Comment by gereonrahnfeld** [comment]
Moritz, Yves and I discussed that we are going to get rid of the translation of the title of the organisation and thus won't have sorting issues anymore. This will happen by only using the title instead of both title and name of an organisation. Please proceed.
