### ISSUE TITLE
View on site from django admin cause 500 and sentry error

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-opin#2136]
**user:** admin
**expected behaviour:** clicking 'view on site' from module page in django admin takes you to page
**behaviour:** it causes a 500 error and triggers santry
**Comment/Question:** this may have an answer https://stackoverflow.com/questions/911887/how-can-i-get-the-django-admins-view-on-site-link-to-work

Sentry error: https://sentry.liqd.net/organizations/liqd/issues/1346/events/?project=8&referrer=alert_email

**Comment by sabinammm** [comment]
The proposed solution in the link is already implemented in opin. 

Because the error said "("Reverse for 'module-detail' not found. 'module-detail' is not a valid view "
 'function or pattern name.') I added the urlpattern as is done here:
<<https://github.com/liqd/a4-meinberlin/blob/87b005a334e8a2404cac786e8336749a547cbe04/meinberlin/apps/projects/urls.py#L20

The also added the module-detail-view as is done here:
https://github.com/liqd/a4-meinberlin/blob/87b005a334e8a2404cac786e8336749a547cbe04/meinberlin/apps/projects/views.py#L381

This retrieves the page and shows it, but also throws a 
Forbidden: /api/follows/this-is-a-text-review/
[14/Mar/2022 14:06:34] "GET /api/follows/this-is-a-text-review/ HTTP/1.1" 403 33
