### ISSUE TITLE
#4410 poll answer can still be edited (but not saved) after phase is over

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#2246]
**URL:** 
https://opin-dev.liqd.net/de/projects/test-poll-187/
**user:** 
participant, logged-out visitor
**expected behaviour:** 
Once the phase for voting is over, the button to „go to survey“ should not be visible and it should not be possible otherwise to go to the edit view of my answer
**behaviour:** 
When the voting phase is over, I can see and click the button „go to survey“ and edit my answer (if I am a logged in user) but not save them. As a logged-out visitor I can also see and click the button „go to survey“ but not fill out/answer anything.
**important screensize:**
all sizes
**device & browser:** 
macOS 11.4, Firefox 89
**Comment/Question:** 

Screenshot?
<img width="658" alt="Bildschirmfoto 2021-07-18 um 15 44 53" src="https://user-images.githubusercontent.com/15341015/126069785-7c350fd8-7974-4e6c-9505-a86c6247143e.png">

**Comment by Rineee** [comment]
@rittermo There was a discussion in meinBerlin what to do when phase is not active: https://github.com/liqd/a4-meinberlin/issues/3736 The outcome was, that the link to the poll should still be there (because helptexts are only shown in the poll and not on the results page), but all inputs should be inactive (this obviously was broken). Is that behaviour also fine for Opin? Otherwise you would have to discuss it with @CarolingerSeilchenspringer again.

I fixed the deactivation of all inputs, so once A4 is updated, they should all be inactive when the phase is not active.
