### ISSUE TITLE
Styling 1-2 Highlited Column CTA Block

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-opin#2429]
**URL:** https://opin.me/en/use-cases/how-to-conduct-a-consultation-for-youth-policy/
**user:** Admin
**expected behaviour:** Pictures with full width are filling the whole box. And the text is not centred.
**behaviour:** Picture is always too small, tried different sizes and formats
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
<img width="1429" alt="Bildschirmfoto 2022-02-09 um 13 55 49" src="https://user-images.githubusercontent.com/52459078/153206304-143b3288-b884-4221-bb80-f913c832603d.png">

**Comment by phillimorland** [comment]
@hello-kathi I think for adding an image we would be much better off using th info block as that was it was made for, the 2 col highlight should not contain images

**Comment by hello-kathi** [comment]
@phillimorland ok let me check tomorrow. The info block looks nice! 

Center Text would be awesome.

**Comment by hello-kathi** [comment]
@phillimorland I will close this issue because of what you wrote. Just FYi

**Comment by phillimorland** [comment]
@hello-kathi thats fine, also just looking at that block when it's used with just text, it does already look centered, should be leave it? I can try to remove the ability to add images so that mistake isn't made again? or we just leave it, what do you think?
![screenshot(22)](https://user-images.githubusercontent.com/5871230/157623078-92ff5d89-c763-48dd-bcd9-2af5f03b9c51.png)

**Comment by hello-kathi** [comment]
@phillimorland Just leave it. It is fine with icons and then we can use it for this. I will try and set up a wiki page in... this year with descriptions how to use blocks in OPIN and then we know and I wont try again to use it with images :D
