### ISSUE TITLE
in project creation Richtext Picture  upload picture is broken /weird

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-opin#2487]
**URL:** https://opin-dev.liqd.net/de/dashboard/offlineevents/projects/morgenstund-hat-drachenmund/
**user:** Admin/ Initiator
**expected behaviour:** During Project creation the image upload is working fine
**behaviour:** Pictures from server uploaded perfectly, all other ways in the image upload leads to broken pictures
**important screensize:**
**device & browser:** 
**Comment/Question:** 
It is only if I upload Pictures, if I use them from the server it is fine
Screenshot?

<img width="1398" alt="Bildschirmfoto 2022-03-15 um 09 06 46" src="https://user-images.githubusercontent.com/52459078/158333221-28bd9b47-f9f9-41c5-992c-8e38ba5a2331.png">
<img width="1398" alt="Bildschirmfoto 2022-03-15 um 09 06 46" src="https://user-images.githubusercontent.com/52459078/158333230-d99fe73d-3283-4ce4-9191-b0007066ef67.png">

**Comment by hello-kathi** [comment]
@phillimorland sorry I didn't saw that you already on this issue. and I changed it a bit:
It doesn't matter in which Text editor during the project set up in the dashboard I try to upload and use pictures, it is not working. Just if I try to use the one from the server, but I really don't know which pics these are.

**Comment by phillimorland** [comment]
@hello-kathi Hey, so this is actually 2 issues I think, one is the black divider and the other is the image being squeezed when not added from the server, if I got you right? 
The image squeeze issue was also in mB https://github.com/liqd/a4-meinberlin/issues/3821 and we fixed it in hacky way which i'll implement here, the other one is bit weirder and i've been investigating but haven't found where the issue is yet.

what do you mean by "Just if I try to use the one from the server, but I really don't know which pics these are." ?

**Comment by hello-kathi** [comment]
@phillimorland ah ok I thought the Black divider and the broken images are the same issues. 
And yes you got that right, it is the black divider and the squeezed Images. Should I write an extra issue for the black divider?
