### ISSUE TITLE
Text Proposal for "Accessible for all registered users on OPIN"

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/a4-opin#431]
Hey a-team, i've been wondering whether the explanation text is easy to understand for our users and initiators. Here, i may propose an updated wording, ready for discussion:
"All projects are open to public: All registered users and everyone else can see and participate in your project. You can chose to set it "private" by unchecking the box below. In private projects you can invite participants yourself and participants can ask for access. Teasers for your project including title and short description will always be visible to everyone though."
What do you think @slomo @MagdaN @rittermo @vellip @damusp @IsabelSensan ?

![bildschirmfoto 2016-11-01 um 18 08 54](https://cloud.githubusercontent.com/assets/13625047/19899496/abc5779c-a060-11e6-9640-75e571956ab5.png)

**Comment by damusp** [comment]
Hey Nadine, 
I think your wording update is helpful, but what actually bothers me here is the checkbox. 
What I don’t like is that the user has to uncheck the box if he wants to set the project to private. Doesn't quite feel right.

I believe that, from a user perspective, radio buttons would be way easier to understand in this case.

**Comment by vellip** [comment]
We discussed this earlier today, and I actually prefer the checkbox, but I
would make the label (which comes after the checkbox) clearer. The checkbox
seems just simpler, and therefore easier to grasp, because it's just one
option instead of two. With a clear label (see below) it would also be
obvious what the other possibility is.

I'd prefer a label like "This project is private, participants have to
request access or be invited." And by default, the checkbox is *not*
checked.

https://uxplanet.org/radio-buttons-ux-design-588e5c0a50dc#.j3xjm6ey9

**Comment by slomo** [comment]
I am with @damusp and would favour a radio button. Since than both cases can be made clear to the user.

   - [ ] all registered opin users
   - [ ] only users invited by you

The text above should also state, that this is not only about participating but also about seeing the projects content.

**Comment by slomo** [comment]
@vellip I also thanks for the link, I think it makes a strong case for radio buttons :smile:

**Comment by NadineKarbach** [comment]
@slomo @vellip @damusp Thanks for the link! Great help in understanding the radio button and the UX philosophy behind it! :-)

**Comment by MagdaN** [comment]
@slomo @damusp what is the solution here?

**Comment by damusp** [comment]
I'm still for radio buttons. 
Also, the labels @slomo suggested earlier fit really well imo.

**Comment by mkind** [comment]
AFAIK radio buttons only provide an exclusive or solution. Is this taken into account in the discussion? The comment https://github.com/liqd/a4-opin/issues/431#issuecomment-257805053 looks more like both can be chosen at the same time.

**Comment by slomo** [comment]
It was intended to be exclusive, because only invited users is a proper subset of all registered users. And in the model it should map to a boolean field anyways.

**Comment by gereonrahnfeld** [comment]
The Feedback we have received so far was not so much about the button itself but about the explanatory text: Some Users think that if they unclick the button the project won't be accessible to anyone anymore. 
The Problem here is that this is not true: if Users unclick the button the project becomes private.

So we need a solution that makes it much clearer what happens here. 

Either we change the explanatory text to something like:
"Only accessible to Users who are invited to participate."

But I think this still leaves the User a bit confused.

Therefore radio buttons seem to be the best solution: 
the two alternatives make it very clear what happens here.
a. private process: only invited users can participate
b. public process: all OPIN-users can participate

Thus, I would go with the last solution.

**Comment by slomo** [comment]
Solved by #874
