### ISSUE TITLE
Rating not possible for user, although rating phase is active (Idea challenge template)

### ISSUE THREAD

**Issue by SabineJulia** [liqd/a4-opin#770]
On opin.me, it is not possible for users to rate ideas, although the collect idea and rating phase are both active (private project).  For moderators it is possible. Here the link to the project, where the problem occurs:
https://opin.me/de/ideas/riqualificazione-giardino/

![rating does not work](https://cloud.githubusercontent.com/assets/24652917/24446589/5558a8ca-146e-11e7-97a0-b90b8a6adba6.JPG)

**Comment by MagdaN** [comment]
@SabineJulia The problem is that only one phase can be active. If both phases have the same time only the on is being chosen. We can either change the type of the first phase, so that everything in that phase is allowed and delete the second phase or ask them to change the dates -> then users can first create and comment ideas and then in the next phase rate the ideas.

**Comment by MagdaN** [comment]
@SabineJulia We changed the phase type in the settings
