### ISSUE TITLE
multiple projects are created 

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#849]
Opin dashboard: if a project is saved after participation-tab, the project is created. If one goes back afterwards and again on safe another project is created. and so on and so on. Is it possible to guarantee that only one project can be created?

**Comment by slomo** [comment]
I would say that is not a bug but rather a feature request, because it works exactly as intended. There is no uniqueness constraints in projects, so if you fill the form the same values (what you do on pressing back) you can submit it again. We could try to validate that you can only use a name once with in an organisation. Then the second attempt would error, and say something like: "Please choose a unique name".

**Comment by gereonrahnfeld** [comment]
Alright, I will leave it as it is for now and close the issue. Will write a US in case there is any future need for this.
